/**
 * server.js
 * ─────────
 * Express server that:
 *  GET /           → serves today's report HTML
 *  GET /download   → streams today's PDF
 *  GET /health     → health check for uptime monitors
 *
 * The report is pre-generated by the daily cron and written to public/report.html.
 * This server just serves it — no runtime AI, no CSV processing at request time.
 */

const express = require("express");
const path = require("path");
const fs = require("fs");

const app = express();
const PORT = process.env.PORT || 3000;

// Serve static files (report.html, any assets)
app.use(express.static(path.join(__dirname, "public")));

// Root → today's report
app.get("/", (req, res) => {
  const reportPath = path.join(__dirname, "public/report.html");
  if (!fs.existsSync(reportPath)) {
    return res.status(503).send(`
      <html><body style="font-family:sans-serif;text-align:center;padding:80px;color:#666">
        <h2>Report not yet generated</h2>
        <p>The daily report will be available after 12:01 AM ET.</p>
      </body></html>
    `);
  }
  res.sendFile(reportPath);
});

// Download today's PDF
app.get("/download", (req, res) => {
  const manifestPath = path.join(__dirname, "data/current-pdf.json");

  if (!fs.existsSync(manifestPath)) {
    return res.status(404).send("No PDF available yet.");
  }

  const { date, path: pdfRelPath } = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const pdfPath = path.join(__dirname, pdfRelPath);

  if (!fs.existsSync(pdfPath)) {
    return res.status(404).send("PDF file not found.");
  }

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="MT-Milestones-${date}.pdf"`);
  fs.createReadStream(pdfPath).pipe(res);
});

// Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

app.listen(PORT, () => {
  console.log(`🎵  MT Milestones running at http://localhost:${PORT}`);
});
